# Generated by Django 4.2.1 on 2023-06-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('category', models.CharField(max_length=100)),
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
            ],
        ),
    ]
